{% set name = "htmldocx" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/htmldocx-{{ version }}.tar.gz
  sha256: b4bcec895f86d7a50ffc7133ca24d85c24f3614db2b37d33a30d9d04654a5486

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - python-docx >=0.8.10
    - beautifulsoup4 >=4.7.0

test:
  imports:
    - htmldocx
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pqzx/html2docx
  summary: Convert html to docx
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
